#!/system/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep DB_USER settings | sed 's/.*=//'`
DB_PASS=`grep DB_PASS settings | sed 's/.*=//'`
DB_NAME=`grep DB_NAME settings | sed 's/.*=//'`

mysql --user=$DB_USER --password=$DB_PASS -e 'create database $DB_NAME;'
