#!/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/.*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/.*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/.*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=$DB_USER\npassword=$DB_PASS" > $TMPFILE

TABLES=$( mysql --defaults-file=$TMPFILE --database=$DB_NAME --execute='SHOW TABLES' | awk '{ print $1 }' | grep -v '^Tables' )
for TABLE in $TABLES; do mysql --defaults-file=$TMPFILE --database=$DB_NAME --execute="DROP TABLE $TABLE"; done

rm -f $TMPFILE
