#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

mysql --defaults-file=$TMPFILE --execute="
	USE $DB_NAME;
	SET FOREIGN_KEY_CHECKS = 0;
	SET GROUP_CONCAT_MAX_LEN = 32768;
	SET @tables = NULL;
	SELECT GROUP_CONCAT( table_name ) INTO @tables
	FROM information_schema.tables
	WHERE table_schema = '$DB_NAME';

	SET @tables = CONCAT( 'DROP TABLE IF EXISTS ', @tables );
	PREPARE stmt FROM @tables;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	SET FOREIGN_KEY_CHECKS = 1;
"

rm -f $TMPFILE
