#!/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/.*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/.*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/.*=//'`

mysqldump --user=$DB_USER --password=$DB_PASS $DB_NAME > $DB_NAME.sql 2>&1 /dev/null | grep -v "Warning: Using a password"
zip $DB_NAME.sql.zip $DB_NAME.sql
rm $DB_NAME.sql
