#!/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

unzip -o $DB_NAME.sql.zip
mysql --defaults-file=$TMPFILE --database=$DB_NAME < $DB_NAME.sql
rm $DB_NAME.sql

rm -f $TMPFILE
