#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
SV_HOST=`grep '^SV_HOST' gatas.cfg | sed 's/[^=]*=//'`
SV_USER=`grep '^SV_USER' gatas.cfg | sed 's/[^=]*=//'`
SV_PORT=`grep '^SV_PORT' gatas.cfg | sed 's/[^=]*=//'`
RM_PATH=`grep '^RM_PATH' gatas.cfg | sed 's/[^=]*=//'`
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`
DB_HOST=`grep '^DB_HOST' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

sh $REAL_DIRECTORY/db_export

scp -P$SV_PORT $DB_NAME.sql.gz $SV_USER@$SV_HOST:$RM_PATH

if [ "$DB_HOST" != "localhost" ]; then
	mysql --defaults-file=$TMPFILE --host="$DB_HOST" --port="$DB_PORT" --execute="DROP DATABASE $DB_NAME; CREATE DATABASE $DB_NAME;"
	gunzip < $DB_NAME.sql.gz | mysql --defaults-file=$TMPFILE --host="$DB_HOST" --port="$DB_PORT" --database="$DB_NAME"
	exit 0
fi

ssh $SV_USER@$SV_HOST -p$SV_PORT bash -c "'
	cd $RM_PATH
	mysql --user=\"$DB_USER\" --password=\"$DB_PASS\" -e \"DROP DATABASE $DB_NAME; CREATE DATABASE $DB_NAME;\"
	gunzip < $DB_NAME.sql.gz | mysql --user=\"$DB_USER\" --password=\"$DB_PASS\" --database=\"$DB_NAME\"
'"
