#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
SCRIPT_SOURCE=${BASH_SOURCE[0]}
SCRIPT_SOURCE=${SCRIPT_SOURCE:-$0}
REAL_DIRECTORY=$( cd "$( dirname "$SCRIPT_SOURCE" )" && pwd )

bash $REAL_DIRECTORY/db_user_create
bash $REAL_DIRECTORY/db_create
