#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
REAL_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
SV_HOST=`grep '^SV_HOST' gatas.cfg | sed 's/[^=]*=//'`
SV_USER=`grep '^SV_USER' gatas.cfg | sed 's/[^=]*=//'`
SV_PORT=`grep '^SV_PORT' gatas.cfg | sed 's/[^=]*=//'`
RM_PATH=`grep '^RM_PATH' gatas.cfg | sed 's/[^=]*=//'`
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`
DB_HOST=`grep '^DB_HOST' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

sh $REAL_DIRECTORY/db_export
sh $REAL_DIRECTORY/scp_local $DB_NAME.sql.gz $RM_PATH

rm -f $TMPFILE
