#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

mysql --user=root --execute="
	GRANT USAGE ON * . * TO '$DB_USER'@'localhost';
	DROP USER '$DB_USER'@'localhost';
	FLUSH PRIVILEGES;
"
