#!/system/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/.*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/.*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/.*=//'`

mysql --user=root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
mysql --user=root -e "GRANT ALL PRIVILEGES ON $DB_NAME . * TO '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
mysql --user=root -e "FLUSH PRIVILEGES;"
