#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
SCRIPT_SOURCE=${BASH_SOURCE[0]}
SCRIPT_SOURCE=${SCRIPT_SOURCE:-$0}
REAL_DIRECTORY=$( cd "$( dirname "$SCRIPT_SOURCE" )" && pwd )
RM_PATH=`grep '^RM_PATH' gatas.cfg | sed 's/[^=]*=//'`
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

sh $REAL_DIRECTORY/db_export
sh $REAL_DIRECTORY/scp_local $DB_NAME.sql.gz $RM_PATH

rm -f $TMPFILE
