#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

while [ $# -gt 0 ]; do
	SUBS=$SUBS"s|$1|$2|g;"
	shift 2
done

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

mysqldump --defaults-file=$TMPFILE $DB_NAME > $TMPFILE.sql
sed -i "$SUBS" $TMPFILE.sql
mysql --defaults-file=$TMPFILE --database=$DB_NAME < $TMPFILE.sql
rm $TMPFILE.sql

rm -f $TMPFILE
