#!/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
J_STABLE=3.6.5
J_VERSION=$1
if [ -z "$J_VERSION" ]; then
	J_VERSION=$J_STABLE
fi

curl -L -O https://github.com/joomla/joomla-cms/releases/download/${J_VERSION}/Joomla_${J_VERSION}-Stable-Full_Package.tar.gz
tar -xzf Joomla_${J_VERSION}-Stable-Full_Package.tar.gz
