#!/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
_PATH=.
F_PERM=0644
D_PERM=0755
if [ -n "$1" ]; then
	_PATH=$1
fi
if [ -n "$2" ]; then
	F_PERM=$2
fi
if [ -n "$3" ]; then
	D_PERM=$3
fi

find $_PATH -type f -exec chmod $F_PERM {} +
find $_PATH -type d -exec chmod $D_PERM {} +
