#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
REAL_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SV_HOST=`grep '^SV_HOST' gatas.cfg | sed 's/[^=]*=//'`
SV_USER=`grep '^SV_USER' gatas.cfg | sed 's/[^=]*=//'`
SV_PORT=`grep '^SV_PORT' gatas.cfg | sed 's/[^=]*=//'`
RM_PATH=`grep '^RM_PATH' gatas.cfg | sed 's/[^=]*=//'`
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`

COMMAND=$1
COMMAND_FILE=$( ls ${REAL_DIRECTORY}/${COMMAND} 2> /dev/null | head -1 )

if [ -r "$COMMAND_FILE" ]; then
	ssh $SV_USER@$SV_HOST -p$SV_PORT "cd $RM_PATH && echo $( eval "echo -e \"`< $COMMAND_FILE`\"" )"
fi
