#!/system/bin/sh

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
DB_USER=`grep DB_USER gatas.cfg | sed 's/.*=//'`
DB_PASS=`grep DB_PASS gatas.cfg | sed 's/.*=//'`
DB_NAME=`grep DB_NAME gatas.cfg | sed 's/.*=//'`

cp wp-config-sample.php wp-config.php

sed -i '/.*DB_NAME.*/s/database_name_here/'$DB_NAME'/' wp-config.php
sed -i '/.*DB_USER.*/s/username_here/'$DB_USER'/' wp-config.php
sed -i '/.*DB_PASSWORD.*/s/password_here/'$DB_PASS'/' wp-config.php
