#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
WP_STABLE=$( curl --silent "https://api.wordpress.org/core/version-check/1.7/" | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^version/ {print $2}' | head -n 1 | sed 's/\(^"\|"$\)//g' )
WP_VERSION=$1

if [ -z "$WP_VERSION" ]; then
	WP_VERSION=$WP_STABLE
fi

curl -O https://wordpress.org/wordpress-${WP_VERSION}.tar.gz
tar -xzf wordpress-${WP_VERSION}.tar.gz --strip-components=1
