#!/bin/bash

###    DO NOT CHANGE anything below    ###
### unless you know what you are doing ###
SCRIPT_SOURCE=${BASH_SOURCE[0]}
SCRIPT_SOURCE=${SCRIPT_SOURCE:-$0}
REAL_DIRECTORY=$( cd "$( dirname "$SCRIPT_SOURCE" )" && pwd )
SV_HOST=`grep '^SV_HOST' gatas.cfg | sed 's/[^=]*=//'`
SV_USER=`grep '^SV_USER' gatas.cfg | sed 's/[^=]*=//'`
SV_PORT=`grep '^SV_PORT' gatas.cfg | sed 's/[^=]*=//'`
RM_PATH=`grep '^RM_PATH' gatas.cfg | sed 's/[^=]*=//'`
DB_USER=`grep '^DB_USER' gatas.cfg | sed 's/[^=]*=//'`
DB_PASS=`grep '^DB_PASS' gatas.cfg | sed 's/[^=]*=//'`
DB_NAME=`grep '^DB_NAME' gatas.cfg | sed 's/[^=]*=//'`
DB_HOST=`grep '^DB_HOST' gatas.cfg | sed 's/[^=]*=//'`
DB_PORT=`grep '^DB_PORT' gatas.cfg | sed 's/[^=]*=//'`

TMPFILE=`mktemp`
echo -e "[client]\nuser=\"$DB_USER\"\npassword=\"$DB_PASS\"" > $TMPFILE

if [ "$DB_HOST" != "localhost" ]; then
	mysqldump --defaults-file=$TMPFILE --host="$DB_HOST" --port="$DB_PORT" "$DB_NAME" | gzip > $DB_NAME.sql.gz
else
	ssh $SV_USER@$SV_HOST -p$SV_PORT "cd $RM_PATH && mysqldump --user=\"$DB_USER\" --password=\"$DB_PASS\" \"$DB_NAME\" | gzip > $DB_NAME.sql.gz"
	bash $REAL_DIRECTORY/scp_remote $RM_PATH/$DB_NAME.sql.gz ./
fi

rm -f $TMPFILE
